# Generated by Django 3.1.3 on 2020-12-23 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank'), ('CC', 'Credit Card'), ('CASH', 'Cash'), ('ASSET', 'Assets'), ('LIBLTY', 'Liability'), ('IVNEST', 'Investment'), ('_INTERNAL', 'Internal Counter Party Accounts')], default='BANK', max_length=10)),
                ('intial_balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=13)),
                ('notes', models.TextField(blank=True)),
                ('closed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.CharField(blank=True, default='', max_length=100)),
                ('symbol_type', models.CharField(choices=[('YAHOO', 'Yahoo Finance'), ('AMFI', 'AMFI MF File'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('asset_class', models.CharField(choices=[('STK', 'Stocks'), ('MFE', 'Mutual Fund - Equity'), ('MFD', 'Mutual Fund - Debt'), ('MFL', 'Mutudl Fund - Liquid'), ('COM', 'Commodity'), ('OTR', 'Others')], default='OTR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('BUY', 'Buy'), ('SELL', 'Sell')], default='EXPENSE', max_length=10)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=13)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=13)),
                ('fee', models.DecimalField(decimal_places=4, default=0.0, max_digits=13)),
                ('payee', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('debit', models.DecimalField(decimal_places=4, default=0.0, max_digits=13)),
                ('credit', models.DecimalField(decimal_places=4, default=0.0, max_digits=13)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_account', to='common.account')),
                ('counter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_counter_account', to='common.account')),
                ('investment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.investment')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=13)),
                ('price_date', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='common.investment')),
            ],
        ),
    ]
